name: Update Top Contributors

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Update Contributors
        run: |
          # Ensure token is properly formatted
          TOKEN="${FCM_GITHUB_TOKEN}"
          echo "Token length: ${#TOKEN}"
          echo "Token prefix: ${TOKEN:0:5}..."

          response=$(curl -v -X POST ${{ secrets.VERCEL_DEPLOYMENT_URL }}/api/updateTopContributors \
          -H "Authorization: Bearer ${TOKEN}" \
          -H "Content-Type: application/json" \
          -w "\n%{http_code}")

          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n1)

          echo "Status code: $status_code"
          echo "Response body: $body"

          if [[ $status_code != 2* ]]; then
            echo "Error: API call failed with status: $status_code"
            exit 1
          fi
        env:
          FCM_GITHUB_TOKEN: ${{ secrets.FCM_GITHUB_TOKEN }}
